### ISSUE TITLE
Error during installation

### ISSUE THREAD

**Issue by hythm7** [zjhmoss/WebDriver2#1]
I'm not able to install the distribution, looks like some modules are missing from the provides section in META file.

```sh
$ pakku add WebDriver2
🧚 ADD: ｢WebDriver2｣
🦋 MTA: ｢WebDriver2:ver<0.1.4>:auth<zef:zoss>:api<5>｣
🦋 FTC: ｢WebDriver2:ver<0.1.4>:auth<zef:zoss>:api<5>｣
🦋 STG: ｢WebDriver2:ver<0.1.4>:auth<zef:zoss>:api<5>｣
🦗 ===SORRY!=== Error while compiling /home/hythm/site#sources/6E09F0755B49FE4B87648AA6321C31DF8B05ACDE (WebDriver2::Driver::Provider)
Could not find WebDriver2::Test::Debugging in:
...
```

I think `WebDriver2::Test::Debugging` (and any other missing modules, if any) need to be added to meta provides so they can be recognized during installation.

**Comment by zjhmoss** [comment]
Thank you.  There were some others, too.  I am working on some changes to the test suite, then will verify install in a clean environment and push changes.

**Comment by zjhmoss** [comment]
It should now install.  The README.md documentation needs to be updated with some changes to usage.  I have some other tasks for a while and will update documentation after.

If you don't mind, could you let me know if it is okay to close the ticket?

**Comment by hythm7** [comment]
Please close the ticket, I'll try installing later today or tomorrow and will let you know if found issue. Thank you.
